version: "3.9"
services:
  server:
    build:
      context: ./Docker/server
      dockerfile: Dockerfile
      target: server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app/server
  client:
    build:
      context: ./Docker/client
      dockerfile: Dockerfile
      target: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
    depends_on:
      - server
networks:
  default:
    driver: bridge